# Generated by Django 4.2.4 on 2023-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0002_camera_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pictures/'),
        ),
    ]
