# Generated by Django 4.2.4 on 2024-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0007_alter_attendance_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
