# Generated by Django 4.2.2 on 2024-03-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyearproject', '0010_temporaryperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryperson',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
